spring.application.name=organize

spring.profiles.active=local

server.port=${PORT:8080}

frontend.url=${FRONTEND_URL:http://localhost:5173}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

groq.api.key=${GROQ_API_KEY}
groq.base-url=https://api.groq.com/openai/v1
groq.model=llama-3.3-70b-versatile